version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8084:8084
    container_name: golang-matching-service
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: golang_docker
    container_name: matching-service-db-mysql
    ports:
      - 3307:3036
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  redis:
    image: redis:latest
    container_name: matching-service-db-redis
    ports:
      - '6379:6379'
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: 
